---
title: "Mosquito-mediated epidemiological effects of malarone treatment"
number-sections: true
format:
  html:
    toc: true
    toc-depth: 4
editor: source
editor_options: 
  chunk_output_type: console
bibliography: references.bib
csl: the-american-naturalist.csl
---

```{r include = FALSE, eval = FALSE}
knitr::purl("malarone.qmd", "tmp.R", documentation = FALSE)
source("tmp.R")
file.remove("tmp.R")
```

## Parasite load and infectiousness

### 1 bite, all human treated

Call $t$ the **time post drug administration** in treated humans and $\tau$ the
**time post mosquito infection**. Call $\alpha(t, \tau)$ the
**transmission blocking activity** (TBA) defined as the percentage reduction of the
number of mosquitoes infected consecutively to 1 blood meal at times $t$ and $\tau$.
Call $\beta(t, \tau)$ the **transmission reducing activity** (TRA) defined as the
percentage reduction of the parasite load in infected mosquitoes consecutively to 1
blood meal at times $t$ and $\tau$. The mean reduction factor of the parasite load due
to TBA and TRA and across the population of infected mosquitoes at times $t$ and $\tau$
then reads

$$
(1 - \alpha(t, \tau))(1 - \beta(t, \tau)).
$$

Call $h(t)$ is the density of probability of the
**distribution of times post drug administration** in the population of treated humans.
The mean reduction factor $l(\tau)$ of parasite load acroos the population of infected
mosquitoes due to
**1 bite on treated people at time $\tau$** then reads

$$
l(\tau) = \int_0^{+\infty}(1 - \alpha(t, \tau))(1 - \beta(t, \tau))h(t)dt.
$$

### Multiple bites, $p\%$ human treated

Call $a$ the **mosquito bite rate**, $p$ the
**proportion of the human population that receives treatment** and $\lambda(\tau)$ the
**mean cumulative reduction factor of the parasite load due to all the bites that have occurred until time $\tau$**.
The fact that each bite on a treated human reduces the parasite load of
$(1 - l(\tau)) \%$ is then conveyed by the following differential equation

$$
\frac{d\lambda}{d\tau} = -(1 - l(\tau)) a p \lambda(\tau).
$$

If we now assume that mosquitoes get infected by bites on untreated humans only then

$$
\lambda(0) = 1,
$$

which leads to the following expression of the mean cumulative reduction factor of the
parasite load at time $\tau$

$$
\lambda(\tau) = \exp\left[-ap\int_0^\tau(1 - l(u))du\right]
$$

### Mean infectiousness reduction

Call $\mu(\lambda)$ the function that converts a **reduction factor of parasite load**
$\lambda$ into a **reduction factor of mosquito infectiousness** and $g$ the
**mosquito death rate** assumed to be independent of the mosquito's age. The mean
reduction factor of mosquito infectiousness in the total mosquito population due to TBA
and TRA can then be expressed as

$$
\theta = \int_0^{+\infty}e^{-g\tau}\mu(\lambda(\tau))d\tau.
$$

## Parasite development and EIP

The EIP is the time at which the parasite reaches maturity for transmission. Call
$z(\tau)$ the dimensionless **level of parasite maturity** at time $\tau$ post
infection and assume it increases from some arbitrary value 0 right after infection:

$$
z(0) = 0
$$

to some arbitrary value 1 once maturity for transmission is reached:

$$
z(\mbox{EIP}) = 1
$$

at a **maturation rate** $\nu$ that is independent of the level of maturity (but that
can depend of the time $\tau$ post infection due in particular to bites on treated
humans):

$$
\frac{dz}{d\tau} = \nu(\tau).
$$

Note that the values 0 and 1 are just convenient choices here and that their exact
values do not matter for the analysis.

### 1 bite, all human treated

Call $\gamma(t, \tau)$ the **reduction factor of the maturation rate** consecutively to
1 blood meal at times $t$ and $\tau$. The mean reduction factor $q(\tau)$ of the
maturation rate across the population of infected mosquitoes due to
**1 bite on treated people at time $\tau$** then reads

$$
q(\tau) = \int_0^{+\infty} \gamma(t, \tau) h(t) dt
$$

### Multiple bites, $p\%$ human treated

In a similar way as done above for the parasite load, we can express the fact that each
bite on treated human reduces the maturation rate by $1 - q(\tau)$ by the following
differential equation

$$
\frac{d\nu}{d\tau} = -(1 - q(\tau))ap\nu(\tau)
$$
Under the same assumption as above that mosquitoes get infected by bites on untreated
humans only then

$$
\nu(0) = \frac{1}{n}
$$

where $n$ is the 
leading to

$$
\nu(\tau) = \frac{1}{n} \exp\left[-ap\int_0^{\tau}(1 - q(u))du\right]
$$

where $n$ is the value of the EIP in absence of treatment in the human population. Now
that we have this, we can implicitly express the average EIP in presence of the
treatment in the human population as the value $T$ satisfying 

$$
\int_0^{T}\nu(\tau)d\tau = 1
$$

<!--
Oocyst size grows linearly as a function
of time $\tau$ post mosquito infection. If EIP is defined as the time post infection at
which the oocysts reach a given size, then a percentage reduction $\gamma(t, \tau)$ of
the oocyst size at a given point in time translates into a percentage reduction
$\delta(t, \tau)$ of the oocsyt growth rate that is proportional to $\gamma(t, \tau)$.
-->

## $R_0$ reduction effect

Putting previous results together, if $R_0$ is the value of the basic reproduction
number in absence of treatment, then, in the presence of treatment in the population,
its expression becomes

$$
\theta e^{(n - T)g} R_0
$$

## Experimental data

Figures 2a and 2c show data of $\alpha(t, \tau = 4\,\mbox{dpi})$ and
$\beta(t, \tau = 4\,\mbox{dpi})$ respectively.

and a good proxy of the level of maturity is the oocyst size. 

For *Plasmodium* parasites a good proxy of the level of maturity is the oocyst size.
